version: "3"
services:
  starknet-node:
    image: eqlabs/pathfinder:latest
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    env_file: # environment file
      - pathfinder-var.env
    volumes:
      - ./pathfinder:/usr/share/pathfinder/data
    ports:
      - 9545:9545
